### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by knro** [rlancaste/kstars-on-osx-craft#5] opened 2021-07-09 10:12 UTC
When running buikd_kstars.sh script, I ran across this:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Installing Homebrew Dependencies.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Warning: python@3.9 3.9.6 is already installed and up-to-date.
To reinstall 3.9.6, run:
  brew reinstall python@3.9
Warning: ninja 1.10.2 is already installed and up-to-date.
To reinstall 1.10.2, run:
  brew reinstall ninja
Warning: gpsd 3.21 is already installed and up-to-date.
To reinstall 3.21, run:
  brew reinstall gpsd
Warning: gnupg 2.3.1_1 is already installed and up-to-date.
To reinstall 2.3.1_1, run:
  brew reinstall gnupg
Warning: subversion 1.14.1_3 is already installed and up-to-date.
To reinstall 1.14.1_3, run:
  brew reinstall subversion
ln: /usr/local/bin/gpg2: Permission denied

**Comment by rlancaste** [comment] 2021-07-09 16:17
Can you check what is currently at  /usr/local/bin/gpg2, is it an alias/link, or a program?  And do you have ownership or is it owned by root?

**Comment by knro** [comment] 2021-07-09 20:34
There is nothing there, I installed it again and this is what I see

Warning: gnupg 2.3.1_1 is already installed and up-to-date.
To reinstall 2.3.1_1, run:
  brew reinstall gnupg
jasem@Jasems-Mac-M1 ~ % brew reinstall gnupg
==> Downloading https://ghcr.io/v2/homebrew/core/gnupg/manifests/2.3.1_1
Already downloaded: /Users/jasem/Library/Caches/Homebrew/downloads/94ccc793ae48e8495887bb4333b2960b892754a908d8912ef67b0620617dfc95--gnupg-2.3.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gnupg/blobs/sha256:fd27ef93bf469e8f5689c372f6b6dba70f2fb777b8056b22e5688b67a146b902
Already downloaded: /Users/jasem/Library/Caches/Homebrew/downloads/15b1313a0211201519f598c641057b3bacdcb348215b2ec43b9cee821b34874f--gnupg--2.3.1_1.arm64_big_sur.bottle.tar.gz
==> Reinstalling gnupg 
==> Pouring gnupg--2.3.1_1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/gnupg/2.3.1_1: 149 files, 13.6MB

**Comment by JuergenTerpe** [comment] 2021-07-25 16:49
I'm running macOS Monterey the latest beta. Maybe this script does not support Monterey yet (then I must wait until the golden master is released). However, my M1 Mac mini has nothing installed inside /usr/local, this is just an empty folder. Not sure, if this folder is not empty when using Big Sur. 

For me this looks like this: 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Installing Homebrew Dependencies.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Warning: python@3.9 3.9.6 is already installed and up-to-date.
To reinstall 3.9.6, run:
  brew reinstall python@3.9
Warning: ninja 1.10.2 is already installed and up-to-date.
To reinstall 1.10.2, run:
  brew reinstall ninja
Warning: gpsd 3.21 is already installed and up-to-date.
To reinstall 3.21, run:
  brew reinstall gpsd
Warning: gnupg 2.3.1_1 is already installed and up-to-date.
To reinstall 2.3.1_1, run:
  brew reinstall gnupg
Warning: subversion 1.14.1_3 is already installed and up-to-date.
To reinstall 1.14.1_3, run:
  brew reinstall subversion
ln: /usr/local/bin/gpg2: No such file or directory

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Line 238:
# This is because gpg is not called gpg2 and translations call on gpg2.  Fix this??
ln -sf /usr/local/bin/gpg /usr/local/bin/gpg2

I installed gnupg as knro did, but this folder is still empty. Any thoughts? :-) 
I should also mention that my new Mac is just one week old, I already installed home-brew and Xcode (and 5 minutes ago Qt), but not so much more. Seems to me that brew installs to another directory now?

**Comment by knro** [comment] 2021-07-25 17:10
The script is making assumption that brew install to /usr/local. Apparently, this has changed recently because on a fresh system brew install to /opt/homebrew, so @rlancaste should probably update the script to account for this.

**Comment by JuergenTerpe** [comment] 2021-07-25 17:13
Thank you, Jasem. 

I just have found gpg was installed to /opt/homebrew/Cellar/gnupg/2.3.1_1 (using "brew info gnupg“). It might take a while… but I will continue. :-)

**Comment by JuergenTerpe** [comment] 2021-07-25 17:24
I have locally changed the script so it will work for me. Now it fails again: 

Fetching logger-colors-1.0.0.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

**Comment by JuergenTerpe** [comment] 2021-07-25 17:27
/Library/Ruby/Gems/2.6.0 write permissions including all sub directories is required.

**Comment by knro** [comment] 2021-07-25 19:10
I actually stopped at the same error and waiting for @rlancaste to fix the script :D so stay tune, we're in the same boat!

**Comment by rlancaste** [comment] 2021-07-26 04:38
I was confused before why it was working fine for me and @knro reported that it was not.  @JuergenTerpe your post helped me understand why it was a problem.  @knro is almost right about the issue.  Apparently, according to what I found, home-brew has decided that they are going to install in different locations for different architectures.  /usr/local is for intel processors which I have and /opt/homebrew is for silicon which I guess you guys have.  To make it work, I guess I will have to have an if statement.

**Comment by rlancaste** [comment] 2021-07-26 04:47
The logger colors issue I am not sure, but it may be related to the above issue I just posted.  The reason I had it run these two lines:

brew install ruby
export PATH=/usr/local/opt/ruby/bin:$PATH

is to solve the very issue you guys just posted.  The system ruby cannot be changed due to permissions, so I installed the homebrew ruby, exported the correct path, and then used gem install logger colors to make sure it installed the logger colors to a ruby that can be changed using gem.  I am assuming that based on what you guys posted, the path I exported must not be right on your system.  Maybe it should be something like

export PATH=/opt/homebrew/ruby/bin:$PATH

can you check?

If so that is another if statement.  There might be more then. . . .

**Comment by knro** [comment] 2021-07-26 12:47
That didn't help, the script needs to accommodate the different prefixes. that's what I got:

```
To reinstall 2.3.1_1, run:
  brew reinstall gnupg
Warning: subversion 1.14.1_3 is already installed and up-to-date.
To reinstall 1.14.1_3, run:
  brew reinstall subversion
Warning: ruby 3.0.2 is already installed and up-to-date.
To reinstall 3.0.2, run:
  brew reinstall ruby
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

```

**Comment by JuergenTerpe** [comment] 2021-07-26 13:53
Just to make progress I edited the script for me locally (without the intention to check it in - would be no good idea with my knowledge :-)). 

Don't know if this might cause other issues, but the script runs much longer: 

# This is because gpg is not called gpg2 and translations call on gpg2.  Fix this??
# ln -sf /usr/local/bin/gpg /usr/local/bin/gpg2
ln -sf /opt/homebrew/Cellar/gnupg/2.3.1_1/bin/gpg /opt/homebrew/Cellar/gnupg/2.3.1_1/bin/gpg2

With this local change I can run the script and it starts to compile (using option -r for safety). Now it fails while compiling openSSL: 

make: *** [all] Error 2
Action: compile for libs/openssl:1.1.1f-1 FAILED
*** Craft all failed: libs/openssl after 24 seconds ***
fatal error: package libs/openssl all failed
Craft stopped with out completing ['libs/openssl', 'libs/expat', 'libs/libffi', 'libs/zlib', 'libs/liblzma', 'libs/libxml2', 'libs/gettext', 'dev-utils/pkg-config', 'python-modules/meson', 'libs/glib', 'libs/dbus', 'libs/libzstd', 'libs/libpng', 'dev-utils/nasm', 'libs/libjpeg-turbo', 'libs/sqlite', 'libs/libbzip2', 'libs/pcre2', 'dev-utils/flex', 'dev-utils/help2man', 'dev-utils/bison', 'dev-utils/flexbison', 'libs/qt5/qtbase', 'libs/libnova', 'libs/cfitsio', 'libs/libusb', 'libs/gsl', 'libs/fftw-double', 'libs/indiserver']

(Maybe) Important hint: I'm using macOS Monterey and Xcode 13 beta 3. To avoid at least any problem due to Xcode beta I downloaded yesterday the latest Xcode 12 version, just to be sure this compiler issue is not related to the beta. But then it was too late to continue. However, this does not help. So I will wait until it is running using Big Sur and then will try with Monterey (unfortunately, I can't go back to Big Sur due to another project I will bring to the iOS App Store this fall).

**Comment by JuergenTerpe** [comment] 2021-08-22 08:51
After your latest changes the script runs much longer. If you don't have the same OS version this might really hard for you as you need to do it blind. The script now stops here:

[722/1071] Linking target gobject/libgobject-2.0.0.dylib
**FAILED: gobject/libgobject-2.0.0.dylib** 
cc  -o gobject/libgobject-2.0.0.dylib gobject/libgobject-2.0.0.dylib.p/meson-generated_.._glib-enumtypes.c.o gobject/libgobject-2.0.0.dylib.p/gatomicarray.c.o gobject/libgobject-2.0.0.dylib.p/gbinding.c.o gobject/libgobject-2.0.0.dylib.p/gboxed.c.o gobject/libgobject-2.0.0.dylib.p/gclosure.c.o gobject/libgobject-2.0.0.dylib.p/genums.c.o gobject/libgobject-2.0.0.dylib.p/gmarshal.c.o gobject/libgobject-2.0.0.dylib.p/gobject.c.o gobject/libgobject-2.0.0.dylib.p/gparam.c.o gobject/libgobject-2.0.0.dylib.p/gparamspecs.c.o gobject/libgobject-2.0.0.dylib.p/gsignal.c.o gobject/libgobject-2.0.0.dylib.p/gsourceclosure.c.o gobject/libgobject-2.0.0.dylib.p/gtype.c.o gobject/libgobject-2.0.0.dylib.p/gtypemodule.c.o gobject/libgobject-2.0.0.dylib.p/gtypeplugin.c.o gobject/libgobject-2.0.0.dylib.p/gvalue.c.o gobject/libgobject-2.0.0.dylib.p/gvaluearray.c.o gobject/libgobject-2.0.0.dylib.p/gvaluetransform.c.o gobject/libgobject-2.0.0.dylib.p/gvaluetypes.c.o -L/Volumes/SamsungSSD/Homes/Users/jt/AstroRoot/craft-root/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -shared -install_name @rpath/libgobject-2.0.0.dylib -compatibility_version 6601 -current_version 6601.4 -Wl,-framework,CoreFoundation -Wl,-framework,Carbon -Wl,-framework,Foundation -Wl,-framework,AppKit -lintl -Wl,-rpath,/Volumes/SamsungSSD/Homes/Users/jt/AstroRoot/craft-root/lib -Wl,-rpath,@loader_path/../glib -Wl,-rpath,@loader_path/../subprojects/proxy-libintl glib/libglib-2.0.0.dylib subprojects/proxy-libintl/libintl.dylib /Volumes/SamsungSSD/Homes/Users/jt/AstroRoot/craft-root/lib/libffi.dylib
ld: warning: ignoring file /Volumes/SamsungSSD/Homes/Users/jt/AstroRoot/craft-root/lib/libffi.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_ffi_call", referenced from:
      _g_cclosure_marshal_generic in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_prep_cif", referenced from:
      _g_cclosure_marshal_generic in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_double", referenced from:
      _value_to_ffi_type in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_float", referenced from:
      _value_to_ffi_type in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_pointer", referenced from:
      _g_cclosure_marshal_generic in gclosure.c.o
      _value_to_ffi_type in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_sint32", referenced from:
      _value_to_ffi_type in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_sint64", referenced from:
      _value_to_ffi_type in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_uint32", referenced from:
      _value_to_ffi_type in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_uint64", referenced from:
      _value_to_ffi_type in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
  "_ffi_type_void", referenced from:
      _g_cclosure_marshal_generic in gclosure.c.o
      _g_cclosure_marshal_generic_va in gclosure.c.o
**ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
[723/1071] Linking target gthread/libgthread-2.0.0.dylib
[724/1071] Linking target gmodule/libgmodule-2.0.0.dylib
[725/1071] Linking target glib/gtester
[726/1071] Linking target glib/tests/1bit-emufutex
[727/1071] Linking target glib/tests/642026-ec
[728/1071] Linking target glib/tests/1bit-mutex
[729/1071] Linking target glib/tests/642026
**ninja: build stopped: subcommand failed.
Action: compile for libs/glib:2.66.4 FAILED**
*** Craft all failed: libs/glib after 49 seconds ***
fatal error: package libs/glib all failed
Craft stopped with out completing ['libs/glib', 'libs/dbus', 'libs/libzstd', 'libs/libpng', 'dev-utils/nasm', 'libs/libjpeg-turbo', 'libs/sqlite', 'libs/libbzip2', 'libs/pcre2', 'dev-utils/flex', 'dev-utils/help2man', 'dev-utils/bison', 'dev-utils/flexbison', 'libs/qt5/qtbase', 'libs/libnova', 'libs/cfitsio', 'libs/libusb', 'libs/gsl', 'libs/fftw-double', 'libs/indiserver']

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Not sure if this is a script issue or something different. But at least you made some progress. :-) 
Thank you!

**Comment by knro** [comment] 2021-08-22 10:20
Yes this is where it fails for me as well :(

**Comment by rlancaste** [comment] 2021-08-22 13:27
Yeah, the main change that I made was to use the home brew prefix command instead of /user/local for any time I called on anything with a full path in the script.  But of course my system is intel so I don’t know how I can run tests for M1. I have parallels but I don’t think it can emulate an arm processor

**Comment by rlancaste** [comment] 2022-01-17 05:47
Hannah has confirmed that QT does not currently support M1 and so for now, support for that architecture will have to wait.  Until then, you can run the script to do everything in x86 mode.  I will add instructions for this.

**Closed as completed by rlancaste** 2022-01-17 05:47 UTC
